
//----------------------------------------------------
// The following code was generated by jh-javacup-1.2 20210807
// Sat Jul 02 12:36:11 CST 2022
//----------------------------------------------------

package edu.tsinghua.ss.thufv.specLang.parse;

/** CUP generated class containing symbol constants. */
public class P4LTLSymbols {
  /* terminals */
  public static final int error = 0;
  public static final int EOF = 1;
  public static final int LPAR = 2;
  public static final int RPAR = 3;
  public static final int MATCH = 4;
  public static final int DROP = 5;
  public static final int ALWAYS = 6;
  public static final int EVENTUALLY = 7;
  public static final int UNTIL = 8;
  public static final int RELEASE = 9;
  public static final int AND = 10;
  public static final int OR = 11;
  public static final int IMPLIES = 12;
  public static final int NEXT = 13;
  public static final int NEG = 14;
  public static final int EQ = 15;
  public static final int NEQ = 16;
  public static final int COMMA = 17;
  public static final int NAME = 18;
  public static final int BVINT = 19;
  public static final int INT = 20;
}

